### ISSUE TITLE
Digital input pins

### ISSUE THREAD

**Issue by glopesdev** [harp-tech/device.hobgoblin#3]
To support basic digital event detection, the board implements a single register `DigitalInputState` whose state is updated via the general GPIO interrupt handler.

### Register schema

```yaml
  DigitalInputState:
    address: 32
    type: U8
    access: Event
    maskType: DigitalInputs
    description: Reflects the state of the digital input lines.
```

#### configure_gpio

```cpp
void configure_gpio(void)
{
    gpio_init_mask(DI_MASK);
    gpio_set_dir_in_masked(DI_MASK);

    gpio_set_irq_callback(gpio_callback);
    gpio_set_irq_enabled(2, GPIO_IRQ_EDGE_FALL | GPIO_IRQ_EDGE_RISE, true);
    gpio_set_irq_enabled(3, GPIO_IRQ_EDGE_FALL | GPIO_IRQ_EDGE_RISE, true);
    gpio_set_irq_enabled(12, GPIO_IRQ_EDGE_FALL | GPIO_IRQ_EDGE_RISE, true);
    gpio_set_irq_enabled(13, GPIO_IRQ_EDGE_FALL | GPIO_IRQ_EDGE_RISE, true);
    gpio_set_irq_enabled(14, GPIO_IRQ_EDGE_FALL | GPIO_IRQ_EDGE_RISE, true);
    irq_set_enabled(IO_IRQ_BANK0, true);
}
```

#### gpio_callback
```cpp
void gpio_callback(uint gpio, uint32_t events)
{
    uint32_t gpio_state = gpio_get_all();
    app_regs.di_state = 0;
    app_regs.di_state |= (gpio_state & 0xC) >> 2;
    app_regs.di_state |= (gpio_state & 0x7000) >> 10;
    HarpCore::send_harp_reply(EVENT, APP_REG_START_ADDRESS);
}
```
