### ISSUE TITLE
Digital output pins

### ISSUE THREAD

**Issue by glopesdev** [harp-tech/device.hobgoblin#4]
To support simple control of digital output lines, the device implements four registers allowing to set, clear, toggle and write the state of all the pins simultaneously.

### Register schema

```yaml
  DigitalOutputSet: &doutput
    address: 33
    type: U8
    access: Write
    maskType: DigitalOutputs
    description: Sets the specified digital output lines.
  DigitalOutputClear:
    <<: *doutput
    address: 34
    access: Write
    description: Clears the specified digital output lines.
  DigitalOutputToggle:
    <<: *doutput
    address: 35
    description: Toggles the specified digital output lines.
  DigitalOutputState:
    <<: *doutput
    address: 36
    description: Writes the state of all digital output lines.
```

#### configure_gpio
```cpp
void configure_gpio(void)
{
    gpio_init_mask(DO_MASK);
    gpio_set_dir_out_masked(DO_MASK);
    gpio_clr_mask(DO_MASK);
}
```

#### write_do_*
```cpp
void write_do_set(msg_t &msg)
{
    HarpCore::copy_msg_payload_to_register(msg);
    gpio_set_mask(app_regs.do_set << DO0_PIN);
    HarpCore::send_harp_reply(WRITE, msg.header.address);
}

void write_do_clear(msg_t &msg)
{
    HarpCore::copy_msg_payload_to_register(msg);
    gpio_clr_mask(app_regs.do_clear << DO0_PIN);
    HarpCore::send_harp_reply(WRITE, msg.header.address);
}

void write_do_toggle(msg_t &msg)
{
    HarpCore::copy_msg_payload_to_register(msg);
    gpio_xor_mask(app_regs.do_toggle << DO0_PIN);
    HarpCore::send_harp_reply(WRITE, msg.header.address);
}

void write_do_state(msg_t &msg)
{
    HarpCore::copy_msg_payload_to_register(msg);
    gpio_put_masked(DO_MASK, app_regs.do_state << DO0_PIN);
    HarpCore::send_harp_reply(WRITE, msg.header.address);
}
```
