### ISSUE TITLE
Pulse train support

### ISSUE THREAD

**Issue by glopesdev** [harp-tech/device.hobgoblin#5]
To support generation of simple pulse trains on the digital output lines, the device implements a set of pulse train repeating timers allowing to drive multiple output lines simultaneously, with support for cancellation.

### Register schema

```yaml
  StartPulseTrain:
    address: 37
    type: U32
    length: 4
    access: Write
    description: Starts a pulse train driving the specified digital output lines.
    payloadSpec:
      DigitalOutput:
        offset: 0
        mask: 0xFF
        maskType: DigitalOutputs
        description: Specifies the digital output lines set by each pulse of the pulse train.
      PulseWidth:
        offset: 1
        defaultValue: 500000
        description: Specifies the duration in microseconds that each pulse is HIGH.
      PulsePeriod:
        offset: 2
        defaultValue: 1000000
        description: Specifies the interval in microseconds between each pulse in the pulse train.
      PulseCount:
        offset: 3
        defaultValue: 1
        description: Specifies the number of pulses in the PWM pulse train. A value of zero signifies an infinite pulse train.
  StopPulseTrain:
    address: 38
    type: U8
    access: [Write, Event]
    maskType: DigitalOutputs
    description: Stops the pulse train running on the specified digital output lines.
```

### Reference implementation

The implementation turns out to be more involved, but the basic idea is to use `add_repeating_timer_us` to drive the periodic pulse train, and `add_alarm_in_us` to set the duration of each pulse within the train.

Events should be optionally sent around start/stop of pulse train and start/stop of each individual pulse, for pairing purposes.
