### ISSUE TITLE
Analog input channels

### ISSUE THREAD

**Issue by glopesdev** [harp-tech/device.hobgoblin#7]
The device should support continuous multi-channel ADC sampling for synchronized monitoring of external non-digital inputs.

### Register schema

```yaml
  AnalogData:
    address: 39
    type: U8
    length: 3
    access: Event
    description: Reports the sampled analog signal on each of the ADC input channels.
    payloadSpec:
      AnalogInput0:
        offset: 0
        description: The analog value sampled from ADC channel 0.
      AnalogInput1:
        offset: 1
        description: The analog value sampled from ADC channel 1.
      AnalogInput2:
        offset: 2
        description: The analog value sampled from ADC channel 2.
```

### Reference implementation

The plan is to use round-robin ADC sampling mode and an automatically retriggered DMA transfer to drive all AD conversions in the background, with a repeating timer configured to pack and send samples at regular intervals to the host.
